global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'my-project'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets:
        - traefik:8080

  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: cadvisor 
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: telegraf
    scrape_interval: 5s
    static_configs:
      - targets: ['telegraf:8125']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
