# playbooks/system_info.yml
---
- name: Playbook yaml
  hosts: all
  tasks:
    - name: JSON generator
      ansible.builtin.setup:

    - name: Create system info JSON
      ansible.builtin.template:
        src: system_info.j2
        dest: /tmp/system_info.json
