---
- name: Install Python dependencies
  apt:
    name:
      - python3-pip
      - python3-psycopg2
    state: present
    update_cache: yes
  become: yes

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes
  become: yes

- name: Ensure PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Create PostgreSQL user
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"
    role_attr_flags: CREATEDB,LOGIN
  become: yes
  become_user: postgres

- name: Create PostgreSQL database
  postgresql_db:
    name: "{{ postgresql_database }}"
    owner: "{{ postgresql_user }}"
  become: yes
  become_user: postgres
