global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

log:
  level: INFO


accessLog:
  filePath: "/logs/traefik.log"
  format: json
  filters:
    statusCodes:
      - "200" # log successful http requests
      - "400-599" # log failed http requests
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop # drop all headers per default
      names:
          User-Agent: keep # log user agent strings

serverTransport:
  insecureSkipVerify: true

entryPoints:
  http:
    address: :80

providers:
  # File provider for connecting things that are outside of docker / defining middleware
  # file:
  #   filename: /etc/traefik/fileConfig.yml
  #   watch: true

  # Docker provider for connecting all apps that are inside of the docker network
  docker:
    watch: true
    network: lab4_acs # Add Your Docker Network Name Here
    exposedByDefault: false
