services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTML_FILE=index1.html
    networks:
      - lab4_acs
    ports:
      - "8081:80"

  backend2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTML_FILE=index2.html
    networks:
      - lab4_acs
    ports:
      - "8082:80"

  nginx:
    image: nginx:latest 
    networks:
      - lab4_acs
    ports:
      - "8080:80" 
    depends_on:
      - backend1
      - backend2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  lab4_acs:
    external: true
